apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-pv
    labels:
        type: local
spec:
    storageClassName: local-storage
    accessModes:
        - ReadWriteOnce     # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
    capacity:
        storage: 10Gi
    local:
        path: /mnt/data
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - agb-worker    # node-name